import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { deflateRawSync } from "node:zlib";
import { parseClassFile } from "../src/intelligence/classfile";
import { parseJar } from "../src/intelligence/jar";
import { Access } from "../src/intelligence/types";

// Generated by JDK 21 javac from tests/fixtures/java, with -parameters -g.
// Keeping the genuine class bytes makes these tests independent of a local JDK.
const fixtures: Record<string, string> = JSON.parse(
  readFileSync(new URL("./fixtures/classfiles.json", import.meta.url), "utf8"),
);
const classBytes = (name: string) => Buffer.from(fixtures[name], "base64");
const buffer = (bytes: Uint8Array): ArrayBuffer =>
  Uint8Array.from(bytes).buffer;

function crc32(bytes: Uint8Array) {
  let value = 0xffffffff;
  for (const byte of bytes) {
    value ^= byte;
    for (let bit = 0; bit < 8; bit++)
      value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1;
  }
  return (value ^ 0xffffffff) >>> 0;
}
function zip(
  entries: [string, Uint8Array][],
  method = 8,
  descriptor = false,
): Buffer {
  const locals: Buffer[] = [],
    central: Buffer[] = [];
  let offset = 0;
  for (const [name, content] of entries) {
    const path = Buffer.from(name),
      data = method === 8 ? deflateRawSync(content) : Buffer.from(content),
      crc = crc32(content),
      flags = 0x800 | (descriptor ? 8 : 0);
    const header = Buffer.alloc(30);
    header.writeUInt32LE(0x04034b50, 0);
    header.writeUInt16LE(20, 4);
    header.writeUInt16LE(flags, 6);
    header.writeUInt16LE(method, 8);
    if (!descriptor) {
      header.writeUInt32LE(crc, 14);
      header.writeUInt32LE(data.length, 18);
      header.writeUInt32LE(content.length, 22);
    }
    header.writeUInt16LE(path.length, 26);
    const trailer = Buffer.alloc(descriptor ? 16 : 0);
    if (descriptor) {
      trailer.writeUInt32LE(0x08074b50, 0);
      trailer.writeUInt32LE(crc, 4);
      trailer.writeUInt32LE(data.length, 8);
      trailer.writeUInt32LE(content.length, 12);
    }
    locals.push(header, path, data, trailer);
    const directory = Buffer.alloc(46);
    directory.writeUInt32LE(0x02014b50, 0);
    directory.writeUInt16LE(20, 4);
    directory.writeUInt16LE(20, 6);
    directory.writeUInt16LE(flags, 8);
    directory.writeUInt16LE(method, 10);
    directory.writeUInt32LE(crc, 16);
    directory.writeUInt32LE(data.length, 20);
    directory.writeUInt32LE(content.length, 24);
    directory.writeUInt16LE(path.length, 28);
    directory.writeUInt32LE(offset, 42);
    central.push(directory, path);
    offset += header.length + path.length + data.length + trailer.length;
  }
  const directory = Buffer.concat(central),
    end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(directory.length, 12);
  end.writeUInt32LE(offset, 16);
  return Buffer.concat([...locals, directory, end]);
}
const allEntries = (): [string, Uint8Array][] =>
  Object.keys(fixtures).map((name) => ["fixture/" + name, classBytes(name)]);

test("javac class metadata retains inheritance, generics, overload descriptors, parameter names and constants", () => {
  const api = parseClassFile(classBytes("Api.class"));
  assert.equal(api.name, "fixture.Api");
  assert.equal(api.superName, "fixture.Base");
  assert.deepEqual(api.interfaces, ["java.lang.Iterable"]);
  assert.equal(
    api.signature,
    "<T:Ljava/lang/Number;>Lfixture/Base<TT;>;Ljava/lang/Iterable<TT;>;",
  );
  const values = api.methods.find((method) => method.name === "values")!;
  assert.equal(values.descriptor, "(Ljava/lang/String;I)Ljava/util/List;");
  assert.equal(values.signature, "(Ljava/lang/String;I)Ljava/util/List<TT;>;");
  assert.equal(values.deprecated, true);
  assert.deepEqual(values.parameterNames, ["label", "limit"]);
  assert.equal(
    api.methods.find((method) => method.name === "<init>")?.descriptor,
    "(I)V",
  );
  assert.equal(
    api.fields.find((field) => field.name === "TEXT")?.constantValue,
    "hello\0한글😀",
  );
  assert.equal(
    api.fields.find((field) => field.name === "LARGE")?.constantValue,
    "9007199254740993",
  );
  assert.equal(
    api.fields.find((field) => field.name === "FRACTION")?.constantValue,
    1.25,
  );
  assert.equal(
    api.fields.find((field) => field.name === "TEXT")!.access & Access.STATIC,
    Access.STATIC,
  );
  assert.equal(
    api.fields.some((field) => field.name === "hidden"),
    false,
  );
  const base = parseClassFile(classBytes("Base.class"));
  assert.equal(
    base.methods.find((method) => method.name === "inherited")?.signature,
    "(TT;)TT;",
  );
  assert.ok(base.methods.some((method) => method.name === "protectedMethod"));
  assert.equal(
    base.methods.some((method) => method.name === "hidden"),
    false,
  );
  assert.ok(
    parseClassFile(classBytes("Point.class")).methods.some(
      (method) => method.name === "toString",
    ),
  );
});

test("JAR parser handles stored/deflated and data descriptor entries; hides private nested and package classes", async () => {
  for (const [method, descriptor] of [
    [0, false],
    [8, false],
    [8, true],
  ] as const) {
    const classes = await parseJar(
      buffer(
        zip(
          [
            ...allEntries(),
            ["assets/ignored.txt", Buffer.from("Not bytecode")],
          ],
          method,
          descriptor,
        ),
      ),
    );
    assert.deepEqual(classes.map((cls) => cls.name).sort(), [
      "fixture.Api",
      "fixture.Api$Nested",
      "fixture.Api$ProtectedNested",
      "fixture.Base",
      "fixture.Point",
    ]);
  }
});

test("multi-release JAR indexing respects the manifest and selected Java runtime version", async () => {
  const api = classBytes("Api.class"),
    alternate = Buffer.from(api);
  // Same-length UTF8 replacement preserves a genuine valid classfile.
  const where = alternate.indexOf(Buffer.from("counter"));
  assert.ok(where >= 0);
  alternate.write("updated", where, "utf8");
  const entries: [string, Uint8Array][] = [
    ["fixture/Api.class", api],
    ["META-INF/versions/21/fixture/Api.class", alternate],
  ];
  const manifest = Buffer.from(
    "Manifest-Version: 1.0\r\nMulti-Release: tr\r\n ue\r\n\r\n",
  );
  const multiRelease = buffer(
    zip([["META-INF/MANIFEST.MF", manifest], ...entries]),
  );
  assert.ok(
    (await parseJar(multiRelease, { javaVersion: 21 }))[0].fields.some(
      (field) => field.name === "updated",
    ),
  );
  assert.ok(
    (await parseJar(multiRelease, { javaVersion: 17 }))[0].fields.some(
      (field) => field.name === "counter",
    ),
  );
  assert.ok(
    (await parseJar(buffer(zip(entries))))[0].fields.some(
      (field) => field.name === "counter",
    ),
  );
});

test("class reader rejects truncation, bad magic, unknown constant tags and malformed modified UTF8", () => {
  const valid = classBytes("Api.class");
  for (const length of [0, 4, 8, 12, 32, 100, valid.length - 1])
    assert.throws(() => parseClassFile(valid.subarray(0, length)));
  const badMagic = Buffer.from(valid);
  badMagic[0] = 0;
  assert.throws(() => parseClassFile(badMagic), /magic/);
  const badTag = Buffer.from(valid);
  badTag[10] = 99;
  assert.throws(() => parseClassFile(badTag), /constant tag/);
  const badUtf8 = Buffer.from(valid),
    nul = badUtf8.indexOf(Buffer.from([0xc0, 0x80]));
  assert.ok(nul > 0);
  badUtf8[nul] = 0xc1;
  assert.throws(() => parseClassFile(badUtf8), /modified UTF-8/);
});

test("JAR rejects corrupt checksums, duplicate names, mismatched class paths and indexing limits", async () => {
  const entry: [string, Uint8Array] = [
    "fixture/Api.class",
    classBytes("Api.class"),
  ];
  const stored = zip([entry], 0),
    corrupt = Buffer.from(stored);
  corrupt[30 + Buffer.byteLength(entry[0]) + 50] ^= 1;
  await assert.rejects(parseJar(buffer(corrupt)), /checksum/);
  await assert.rejects(parseJar(buffer(zip([entry, entry]))), /Duplicate/);
  await assert.rejects(
    parseJar(buffer(zip([["fixture/Wrong.class", entry[1]]]))),
    /class name/,
  );
  await assert.rejects(
    parseJar(buffer(zip([["../Api.class", entry[1]]]))),
    /class path/,
  );
  await assert.rejects(
    parseJar(buffer(stored), { maxClassBytes: 1 }),
    /size limit/,
  );
  await assert.rejects(
    parseJar(buffer(zip(allEntries())), { maxEntries: 1 }),
    /too many/,
  );
  await assert.rejects(
    parseJar(buffer(stored), { maxTotalBytes: 1 }),
    /size limit/,
  );
  await assert.rejects(
    parseJar(buffer(stored.subarray(0, stored.length - 1))),
    /central directory/,
  );
});

test("decompression enforces declared sizes before accepting an entry", async () => {
  const bytes = zip([["fixture/Api.class", classBytes("Api.class")]], 8, true);
  const directory = bytes.readUInt32LE(bytes.length - 22 + 16);
  bytes.writeUInt32LE(1, directory + 24);
  await assert.rejects(parseJar(buffer(bytes)), /expanded beyond/);
});
